/*
 * This file was adapted from the tinyVars repository provided in class.
 * Original source: https://github.students.cs.ubc.ca/CPSC410-2024W-T2/tinyVars
 * Modifications have been made to implement the FileScript DSL.
 */

parser grammar FileScriptParser;
options { tokenVocab=FileScriptLexer; }

program: NEWLINE* stmt* EOF;

stmt: ( assign | if | while | fnCall ) ( NEWLINE+ | EOF );
assign: varname IS exp;
if: IF exp THEN block (ELSE block)? END;
while: WHILE exp DO block END;
block: NEWLINE+ stmt*;
fnCall: fnName LP (args)? RP;

/* Start Code Generated by ChatGPT on 2025-01-31 */
exp: orExp;
orExp: andExp (OR andExp )*;
andExp: relExp (AND relExp )*;
relExp: addExp ( (EQ | NE | GT | LT | GE | LE) addExp )*;
addExp: mulExp ( (ADD | SUB) mulExp )*;
mulExp: baseExp ( (MUL | DIV) baseExp )*;
/* End Code Generated by ChatGPT on 2025-01-31 */

baseExp: NUM | TEXT | TRUE | FALSE | varname | fnCallExp | stack;
fnCallExp: fnCall;
args: exp (COMMA exp)*;
varname: NAME index?;
fnName: NAME;
stack: STACK;
index: LB exp RB;
